/**
 * Publishing the static build into the git repository the site is served from.
 *
 * `bun run build:static` writes `out/`; this replaces the contents of a sibling repository
 * with that directory and commits the result. The replacement is a clear-then-copy rather
 * than a merge, so a page that stops existing stops being served — which means the clear has
 * to spare `.git`, and has to refuse to run anywhere that is not the root of a repository of
 * its own.
 *
 * The pure parts live here, apart from the side effects, so the arguments, the message and
 * the "everything except `.git`" rule can be unit tested without a build or a repository.
 */
import { spawn } from 'node:child_process'
import { cp, readdir, rm } from 'node:fs/promises'
import path from 'node:path'

/** Where the built site is published unless `STATIC_PUBLISH_DIR` says otherwise. */
export const DEFAULT_PUBLISH_DIR = '../code-art-static'

/** The one entry a clear must never remove: the repository it is publishing into. */
const PRESERVED = new Set(['.git'])

export interface PublishOptions {
  /** The repository to publish into, or `null` to build without publishing. */
  directory: string | null
  /** Whether a commit is pushed to its remote. */
  push: boolean
}

export interface BuildSummary {
  pages: number
  assets: number
  media: number
}

/**
 * What the command line and environment ask for. `--no-publish` (or an empty
 * `STATIC_PUBLISH_DIR`) builds `out/` and stops there; `--no-push` commits locally.
 */
export const publishOptions = (
  argv: readonly string[],
  env: Record<string, string | undefined> = {},
): PublishOptions => {
  const directory = env.STATIC_PUBLISH_DIR ?? DEFAULT_PUBLISH_DIR

  if (argv.includes('--no-publish') || directory.length === 0)
    return { directory: null, push: false }

  return { directory, push: !argv.includes('--no-push') }
}

/** Everything in the published repository that a clear replaces. */
export const entriesToClear = (names: readonly string[]): string[] =>
  names.filter((name) => !PRESERVED.has(name))

/** The commit written for a build, describing what the crawl produced. */
export const commitMessage = ({ pages, assets, media }: BuildSummary): string =>
  [
    'chore: publish static site build',
    '',
    `${pages} pages, ${assets} assets, ${media} media files, generated by ` +
      '`bun run build:static`.',
  ].join('\n')

/** Runs a command in `cwd` and resolves with its stdout, trimmed. */
const capture = (command: string, args: string[], cwd: string): Promise<string> =>
  new Promise((resolve, reject) => {
    const child = spawn(command, args, { cwd, stdio: ['ignore', 'pipe', 'inherit'] })

    let stdout = ''
    child.stdout.on('data', (chunk: Buffer) => {
      stdout += chunk.toString('utf8')
    })

    child.on('error', reject)
    child.on('exit', (code) =>
      code === 0
        ? resolve(stdout.trim())
        : reject(new Error(`\`${command} ${args.join(' ')}\` exited ${code}`)),
    )
  })

const git = (args: string[], cwd: string): Promise<string> => capture('git', args, cwd)

/**
 * Resolves the repository root at `directory`, or throws. Publishing deletes everything it
 * finds, so it only ever runs at the top of a repository — not in a plain directory, and not
 * in a subdirectory of some larger checkout that happens to sit at the configured path.
 */
const repositoryRoot = async (directory: string): Promise<string> => {
  const root = await git(['rev-parse', '--show-toplevel'], directory).catch(() => null)

  if (root === null) throw new Error(`${directory} is not a git repository`)
  if (path.resolve(root) !== path.resolve(directory)) {
    throw new Error(`${directory} is inside the repository at ${root}, not the root of one`)
  }

  return path.resolve(root)
}

/** Replaces the repository's contents with `source`, keeping `.git`. */
const replaceContents = async (root: string, source: string): Promise<void> => {
  const entries = entriesToClear(await readdir(root))
  await Promise.all(
    entries.map((entry) => rm(path.join(root, entry), { recursive: true, force: true })),
  )
  await cp(source, root, { recursive: true })
}

/** The remote a commit is pushed to: `origin` when it exists, otherwise the first one. */
const pushRemote = async (root: string): Promise<string | null> => {
  const remotes = (await git(['remote'], root)).split('\n').filter(Boolean)
  if (remotes.length === 0) return null
  return remotes.includes('origin') ? 'origin' : remotes[0]
}

/**
 * Copies `source` over the repository at `directory` and commits the difference. Does
 * nothing beyond the copy when the build is identical to what is already published, so a
 * rebuild of unchanged content leaves no empty commit behind.
 */
export const publish = async (
  source: string,
  { directory, push }: PublishOptions,
  summary: BuildSummary,
): Promise<void> => {
  if (directory === null) return

  const root = await repositoryRoot(directory)

  console.log(`> publishing to ${root}`)
  await replaceContents(root, source)

  await git(['add', '--all'], root)
  const changes = await git(['status', '--porcelain'], root)

  if (changes.length === 0) {
    console.log('  nothing changed since the last publish')
    return
  }

  await git(['commit', '--message', commitMessage(summary)], root)
  const commit = await git(['rev-parse', '--short', 'HEAD'], root)
  console.log(`  committed ${commit} (${changes.split('\n').length} files)`)

  if (!push) {
    console.log('  --no-push: left the commit unpushed')
    return
  }

  const branch = await git(['rev-parse', '--abbrev-ref', 'HEAD'], root)
  const remote = await pushRemote(root)

  if (remote === null || branch === 'HEAD') {
    console.warn(`  ! not pushed: ${remote === null ? 'no remote' : 'detached HEAD'}`)
    return
  }

  await git(['push', remote, branch], root)
  console.log(`  pushed ${branch} to ${remote}`)
}
